### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by romanbsd**

### CODE REVIEW

**Comment by marat-y** [comment]
Any progress on merging this one please? Still cannot use debase with latest ruby

**Comment by ZimbiX** [comment]
Once rebased, the tests run successfully for me on Ruby 3.3.6 :+1:

```diff
diff --git a/ext/debase_internals.c b/ext/debase_internals.c
index b940563..730bba4 100644
--- a/ext/debase_internals.c
+++ b/ext/debase_internals.c
@@ -316,7 +316,7 @@ call_at_line(debug_context_t *context, char *file, int line, VALUE context_objec
 int count_stack_size() {
     rb_thread_t *thread = ruby_current_thread;
     rb_control_frame_t *last_cfp = TH_CFP(thread);
-    const rb_control_frame_t *start_cfp = RUBY_VM_END_CONTROL_FRAME(TH_INFO(thread));
+    const rb_control_frame_t *start_cfp = (rb_control_frame_t *)RUBY_VM_END_CONTROL_FRAME(TH_INFO(thread));
     const rb_control_frame_t *cfp;
 
     ptrdiff_t size, i;
@@ -715,12 +715,14 @@ Debase_enable_file_filtering(VALUE self, VALUE value)
         }
     }
 #else
-      static void
+      static VALUE
       Debase_set_trace_flag_to_iseq(VALUE self, VALUE rb_iseq) {
+        return Qnil;
       }
 
-      static void
+      static VALUE
       Debase_unset_trace_flags(VALUE self, VALUE rb_iseq) {
+        return Qnil;
       }
 #endif
```

**Comment by romanbsd** [comment]
rebased

**Comment by stanhu** [comment]
@hurricup Would you mind tagging a new release? I've validated `master` works on my system now, but debase 0.2.7 does not.
